/**
 * Minimal DOM construction helpers.
 *
 * The UI is small enough that a virtual DOM would cost more in concepts than it
 * saves in code. These three functions cover everything the interface needs.
 */

type Attributes = Record<string, string | number | boolean | EventListener | undefined | null>;
type Child = Node | string | null | undefined | false;

/**
 * Creates an element.
 *
 * Keys beginning with `on` are attached as event listeners; `class`, `text` and
 * `html` are special-cased; everything else becomes an attribute. Boolean
 * `false` and nullish values remove the attribute entirely, so conditional
 * attributes can be written inline without a ternary.
 */
export function el<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  attributes: Attributes = {},
  ...children: Child[]
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);

  for (const [key, value] of Object.entries(attributes)) {
    if (value === undefined || value === null || value === false) continue;

    if (key.startsWith('on') && typeof value === 'function') {
      node.addEventListener(key.slice(2).toLowerCase(), value as EventListener);
    } else if (key === 'class') {
      node.className = String(value);
    } else if (key === 'text') {
      node.textContent = String(value);
    } else if (key === 'html') {
      // Only ever called with literals defined in this codebase, never with
      // user content — board names and text go through `text` above.
      node.innerHTML = String(value);
    } else if (value === true) {
      node.setAttribute(key, '');
    } else {
      node.setAttribute(key, String(value));
    }
  }

  for (const child of children) {
    if (child === null || child === undefined || child === false) continue;
    node.append(typeof child === 'string' ? document.createTextNode(child) : child);
  }

  return node;
}

/**
 * Inline SVG icon from the markup in `ICONS`, sized to the current font.
 *
 * `markup` is the *inner* content of a 24x24 icon, not a single path's `d`.
 * That distinction is the whole reason this function changed: a real icon set
 * routinely draws one glyph from several elements — a rect and two paths, a
 * circle and a line — and the previous single-`<path>` construction quietly
 * could not express any of them.
 *
 * `innerHTML` is safe for the same reason it is in `el()` above: every value
 * comes from `icons.ts`, which is generated by `scripts/build-icons.mjs` from a
 * strict element and attribute whitelist and never sees user content. The
 * whitelist is what keeps that true as icons are added, rather than merely true
 * today.
 *
 * The stroke width matches what Lucide draws for, so the glyphs have the weight
 * they were designed with.
 */
export function icon(markup: string, size = 18): SVGSVGElement {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('width', String(size));
  svg.setAttribute('height', String(size));
  svg.setAttribute('fill', 'none');
  svg.setAttribute('stroke', 'currentColor');
  svg.setAttribute('stroke-width', '2');
  svg.setAttribute('stroke-linecap', 'round');
  svg.setAttribute('stroke-linejoin', 'round');
  svg.setAttribute('aria-hidden', 'true');
  svg.innerHTML = markup;
  return svg;
}

export function clear(node: Element): void {
  while (node.firstChild) node.firstChild.remove();
}

/** True on macOS, so shortcut hints can show ⌘ rather than Ctrl. */
export const IS_MAC = typeof navigator !== 'undefined' && /Mac|iPhone|iPad/.test(navigator.platform || navigator.userAgent);

export const MOD_KEY = IS_MAC ? '⌘' : 'Ctrl';

/**
 * True when the primary pointer is a finger rather than a mouse or stylus.
 *
 * Note that `IS_MAC` above cannot answer this: iPadOS reports
 * `navigator.platform === 'MacIntel'` and a desktop Safari user agent, so an
 * iPad is indistinguishable from a Mac that way. The pointer media query asks
 * the question that actually matters — how accurate the pointing device is —
 * and `maxTouchPoints` covers browsers that answer it conservatively.
 */
export const IS_COARSE_POINTER =
  typeof window !== 'undefined' &&
  (window.matchMedia?.('(pointer: coarse)').matches === true ||
    (typeof navigator !== 'undefined' && navigator.maxTouchPoints > 0));

/**
 * Calls `onOutside` for the next presses that land outside `inside`, until the
 * returned function is called. For an in-place editor that has to close itself
 * when the user moves on.
 *
 * Blur is not enough to end an edit. Whether pressing a button moves focus
 * out of a field is a platform convention, and on a touch screen a tap on the
 * canvas may not move focus at all. See "Blur is a platform convention" in
 * LEARNINGS.md.
 *
 * Two timing rules, each of which broke something once:
 *
 *   - Registered a TASK later. The press that opened the editor is usually
 *     still bubbling towards `window`, and a listener added synchronously
 *     would dismiss the editor it just opened. A microtask is not enough: the
 *     dispatcher drains the microtask queue between listeners, so the handler
 *     would still run for the same event.
 *   - On the BUBBLE phase, not capture, so a press on the canvas is handled
 *     once, by the controller, which also swallows it so the dismissing press
 *     does not start a gesture.
 *
 * `inside` should stop its own `pointerdown` from propagating, or a press in
 * the editor would bubble here too. The containment check is a second guard.
 */
export function listenForOutsidePress(inside: HTMLElement, onOutside: () => void): () => void {
  const onPointerDown = (event: PointerEvent): void => {
    if (inside.contains(event.target as Node)) return;
    onOutside();
  };
  let timer: ReturnType<typeof setTimeout> | null = setTimeout(() => {
    timer = null;
    window.addEventListener('pointerdown', onPointerDown);
  }, 0);

  return () => {
    if (timer !== null) clearTimeout(timer);
    timer = null;
    window.removeEventListener('pointerdown', onPointerDown);
  };
}
